### ISSUE TITLE
Example does not work for "runs-on: windows-latest" ?

### ISSUE THREAD

**Issue by StefH** [einaregilsson/build-number#2]
When using `runs-on: windows-latest`, and this code
```
echo Build number is $BUILD_NUMBER
```

I get this:
![image](https://user-images.githubusercontent.com/249938/69136555-56399d80-0abb-11ea-80c0-a327543428ba.png)

I could only solve this by using the **id: buildnumber**, like:
```
steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v1
      id: buildnumber
      with:
        token: ${{secrets.github_token}}   
    
    - name: Print new build number
      run: echo "Build number is ${{ steps.buildnumber.outputs.build_number }}"
```

Is this a known issue? And maybe update your readme?

**Comment by einaregilsson** [comment]
Just hadn't tested on Windows. Fixed now, thanks :)

**Comment by StefH** [comment]
Sorry, your update is not correct.

If you want to use `${{ steps.buildnumber.outputs.build_number }}`, you also need to add `id: buildnumber` to the step before.

Also I wonder if this text is valid because in my solution (windows-latest) using the **BUILD_NUMBER** does not work.

> After that runs the subsequent steps in your job will have the environment variable BUILD_NUMBER available. If you prefer to be more explicit you can use the output of the step, like so:

**Comment by einaregilsson** [comment]
Ok, added the ```id: buildnumber```

I use the "official" GitHub Actions way of setting an environment variable, and it works on Linux, not sure if Windows handles things differently. How are you accessing the environment variable in the subsequent steps? I'd assume at least in scripts you might need to use ```%BUILD_NUMBER%``` instead of ```$BUILD_NUMBER``` if you're using CMD as the interpreter.

**Comment by StefH** [comment]
I got it resolved: the solution for windows can be done in 2 ways
``` yml
 - name: Print new build number
      run: |
        echo "Build number is ${{ steps.buildnumber.outputs.build_number }}"
        echo "Build number is ${env:BUILD_NUMBER}"
```

The output looks like:
![image](https://user-images.githubusercontent.com/249938/69167270-f6f87f00-0af4-11ea-90f1-b181cb187514.png)


see also
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
